### ISSUE TITLE
Autodetect unstripped ReMIX files

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#124]
I think this would be a useful thing to have, specifically for the game engine so far. It would also be a good start to finally interweave our tools together. Upon launching the game engine if it detects ReMIX files but notices they are not stripped, prompt the user to strip them before finally starting the game.

**Comment by Xeeynamo** [comment]
easy done #126

**Comment by Rikux3** [comment]
Fixed with #126
