### ISSUE TITLE
Upon Compiling, Multiple Executables are Generated

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#15]
As title states, multiple executables of the same program are created. An example would be:
`.\OpenKh\bin\Debug\net472\OpenKh.Tools.LevelUpEditor.exe`
Also present at:
`.\OpenKh\OpenKh.Tools.LevelUpEditor\obj\Debug\net472\OpenKh.Tools.LevelUpEditor.exe`

I'm unsure if this is actually an error at compile time, but it seems unnecessary and strange nonetheless, taking up unnecessary disk space. Executables between both locations are functionally identical, only the lattermost won't run immediately after compiling due to the missing library files in the folder. Supplying the libraries or moving the exe into a folder with the libraries allows it to run.

**Comment by Xeeynamo** [comment]
Good question! the `obj/` folder is an intermediate folder used by Visual Studio on compile time. After compilation, all the useful objects will be copied into `bin/` and not moved. This is the default Visual Studio behaviour.

The content in `bin/` is the one used for distribution. If you want to free-up space, you can execute a "Clean solution" from Visual Studio, or run the command `git clean -xdf" from any terminal/command prompt.
