### ISSUE TITLE
OpenKh.Command.ImgTool cannot mix multiple bit depth images

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#162]
Using the tool to create an IMZ file is easy enough, but using it to generate an IMZ that mixes more than one bit depth gives unusable files. Attached is one such file. Inside the IMZ, images 0, 1, 4, and 7 are 8bpp. The rest are 4bpp. 
It crashes all new viewers and editors as well as old, deprecated editors and viewers from years ago, but only after loading the 4bpp images. HOWEVER, 4bpp generation is not the cause. If I make images 0~6 4bpp and images 7 and 8 8bpp or 32bpp, every image except 7 and 8 will load fine. The problem only occurs on the first and subsequent images with a differing bit depth than the first.
[title_aq_test.zip](https://github.com/Xeeynamo/OpenKh/files/4935048/title_aq_test.zip)

**Comment by kenjiuno** [comment]
Thanks for reporting!

I noticed the reason: https://github.com/Xeeynamo/OpenKh/blob/3c0c1b2ea058a79114b188a641b2c04d33a44c85/OpenKh.Command.ImgTool/Utils/ImgdBitmapUtil.cs#L222

For 4bpp bitmap, it needs `src.Width * src.Height / 2` (not `src.Width * src.Height`)

It is bug of `OpenKh.Command.ImgTool` I have written.

For example `KH2 Image Editor.exe` seems to rely on the field `0c | uint32_t | Bitmap size in bytes` defined in `.imd` (See https://openkh.dev/kh2/file/type/image.html#imgd)

512 x 512 x 4bpp bitmap needs to be `131,072` bytes length. However ImgTool writes `262,144` to `Bitmap size in bytes` field, and `262,144` bytes bitmap actually.

I need to fix it.

**Comment by kenjiuno** [comment]
Also there is another bug (2 pixels order in one byte) in 4bpp imd/imz encoding...

![2020-07-18_14h41_31](https://user-images.githubusercontent.com/5955540/87845725-d04d4b00-c904-11ea-83e6-dc7d7eca9f2b.png)
