### ISSUE TITLE
Sprite group editor (OpenKh.Tools.LayoutEditor) needs a "remove sprite part" function

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#170]
The layout editor is able to add new sprites but cannot remove sprites. Would be great if this could be fixed. 
![image](https://user-images.githubusercontent.com/20749232/88047532-c489a080-cb1f-11ea-9a54-eb6994d1bd41.png)

**Comment by Xeeynamo** [comment]
Can you confirm this has been implemented as you expected?

**Comment by Vladabdf** [comment]
Ah, you're right. Fixed with #194.
