### ISSUE TITLE
Kh2SystemEditor: saving without changes modifes the file

### ISSUE THREAD

**Issue by Rikux3** [Xeeynamo/OpenKh#174]
From the looks of it, something in FTST is shifted by 1.
Load 2FM 03system.bin, and directly save it to reproduce.

![grafik](https://user-images.githubusercontent.com/29046361/88160489-fc234600-cc0e-11ea-8377-ffc640eec372.png)

[KH2.zip](https://github.com/Xeeynamo/OpenKh/files/4959192/KH2.zip)

**Comment by Xeeynamo** [comment]
Very weird. we have `FstsTableTests.ShouldWriteTheExactSameFile` which verifies that the parser is not broken. Maybe there is something wrong with the tool?

**Comment by Rikux3** [comment]
I've encountered another bug: Open 03system, change any value in Item (i've changed the description id from one item) and then save. The internal sub-files now have other offset and the files gets padded out.
[03system-item-change.zip](https://github.com/Xeeynamo/OpenKh/files/4960021/03system-item-change.zip)

**Comment by kenjiuno** [comment]
> From the looks of it, something in FTST is shifted by 1.

I'll check it

**Comment by kenjiuno** [comment]
Hmm.

![image](https://user-images.githubusercontent.com/5955540/88250035-437a0700-cce1-11ea-94f9-625b1dec3280.png)

**Comment by kenjiuno** [comment]
> I've encountered another bug: Open 03system, change any value in Item (i've changed the description id from one item) and then save. The internal sub-files now have other offset and the files gets padded out.

I'll check this

**Comment by kenjiuno** [comment]
I have put your `03system-my-item-change.bin` into Kaitai Web IDE. [kh2_03_system_bin.zip](https://github.com/Xeeynamo/OpenKh/files/4963817/kh2_03_system_bin.zip)


It looks the count of Item `entry` is decreased from 535 to 53.


![2020-07-23_13h13_21](https://user-images.githubusercontent.com/5955540/88251809-f4cf6b80-cce6-11ea-942b-b9085f68a153.png)

![2020-07-23_13h13_39](https://user-images.githubusercontent.com/5955540/88251815-f9941f80-cce6-11ea-84a6-c92309f9e9ff.png)

Are there special operations other than changing description id? I couldn't reproduce the item count decreasement.

**Comment by Rikux3** [comment]
After checking the System editor in the latest version, i also can not reproduce the item count problem anymore. Maybe i was using a debug version or something, please ignore that.

I found the problem for the FTST file though. When saving the file, you do a Enumberable.Range and start with 0 (FtstViewModel.cs, Line 109).
![grafik](https://user-images.githubusercontent.com/29046361/88257881-16b4f800-ccbf-11ea-9c89-4bb6df6670d9.png)

**Comment by kenjiuno** [comment]
This is the cause of id shift:

![2020-07-23_16h24_53](https://user-images.githubusercontent.com/5955540/88261340-10e00680-cd01-11ea-834c-4b53628b90c6.png)

The editor also needs to keep palette id

![2020-07-23_16h25_18](https://user-images.githubusercontent.com/5955540/88261359-1a696e80-cd01-11ea-98a9-43ae2665cc24.png)

**Comment by Xeeynamo** [comment]
So, I reached two conclusions:
1) The FTST functionality in the GUI has to be re-designed. The FTST is not a list of worlds but a list of colors where every entry is a world. Creating a grid view would represent those information easily.
2) @Rikux3 Since the 03system editor damage the original file, do you want to do a pull request that disables FTST functionality? I will restore it and make it properly working later on.

**Comment by Rikux3** [comment]
Sure, i can do that.
