### ISSUE TITLE
Clicks go through A, L, and P timeline options in Layout Editor

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#176]
Upon scrolling the timeline down, when the "Add new", "Force loop", and "Pause" buttons line up with buttons underneath, clicks activate both the button hovered over and the one underneath it. Sometimes the tooltip for both appears too, showing the problem like so:
![image](https://user-images.githubusercontent.com/20749232/88274100-32ad9f00-cca9-11ea-907a-62f8f1edc4c0.png)

So far, this has caused me to accidentally duplicate animations, show only one animation layer unintentionally, and hide layers without intending to.

**Comment by Xeeynamo** [comment]
This bug is really a bad one. I will look into fixing it ASAP.
