### ISSUE TITLE
MapEditor text corruption when opening a .map file

### ISSUE THREAD

**Issue by TheStibblr** [Xeeynamo/OpenKh#215]
[videoforXeynamo.zip](https://github.com/Xeeynamo/OpenKh/files/5056390/videoforXeynamo.zip)

Video shows it all really

**Comment by Xeeynamo** [comment]
Hey. Please comment all the issues in #214 as it has not been officially released yet. But I acknowledged the issue, thanks for the feedback! Try to open the game folder first (CTRL+O) and then any map individually. For now, I am closing here, but be free to continue to comment on this specific matter and everything else in #214 👍
