### ISSUE TITLE
Map Studio not saving extracted game folder location

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#269]
I can't find any sort of config file for the Map Studio, so as expected, upon reopening the program it generates a prompt about how the contents of the game cannot be found. This is easily fixed by specifying the location within the program, but the user has to do this every time they start Map Studio.
![image](https://user-images.githubusercontent.com/20749232/98449862-8f708080-2105-11eb-8e41-7cd663afa8b7.png)

**Comment by kenjiuno** [comment]
I'm curious to know, too

![2020-11-12_23h12_07](https://user-images.githubusercontent.com/5955540/98950555-7ff59b00-253c-11eb-9836-e00598a69624.png)

Ahh it is hard coded `D:\Hacking\KH2\export_fm` for now...

**Comment by Xeeynamo** [comment]
Ooops my fault... It should be removed really. I will fix it in a PR as soon as possible
