### ISSUE TITLE
OpenKh.Tools.Kh2TextEditor - event/system fonts display with a weird width

### ISSUE THREAD

**Issue by pablo5425** [Xeeynamo/OpenKh#287]

**Comment by Xeeynamo** [comment]
could you attach a screenshot too?

**Comment by pablo5425** [comment]
![image](https://user-images.githubusercontent.com/34631489/99295702-0b757180-2846-11eb-8485-5e62c6481313.png)
![image](https://user-images.githubusercontent.com/34631489/99295733-13cdac80-2846-11eb-8d9c-ec7e8bc6369f.png)
including both fonts just in case

**Comment by Vladabdf** [comment]
By chance did you include to fontimage and fontinfo bar files from PAL KH2?

**Comment by Xeeynamo** [comment]
Fixed in #305
