### ISSUE TITLE
KH2TextEditor not displaying icons correctly

### ISSUE THREAD

**Issue by pablo5425** [Xeeynamo/OpenKh#319]
all of game icons appear glitched when using both system and event fonts
![image](https://user-images.githubusercontent.com/34631489/102118017-68f9df80-3e3f-11eb-9aa9-7d77f3587086.png)
![image](https://user-images.githubusercontent.com/34631489/102118163-9d6d9b80-3e3f-11eb-95e5-8f71d49cd7de.png)
![image](https://user-images.githubusercontent.com/34631489/102118179-a3fc1300-3e3f-11eb-8ae2-b7e8a0f14a1e.png)
![image](https://user-images.githubusercontent.com/34631489/102118199-a9595d80-3e3f-11eb-8424-676b0f8e1da5.png)

**Comment by Xeeynamo** [comment]
Thanks for the feedback 👍 . Did you try very old builds to see if they have the same problem? It might help to speed up finding the bug. I would jump month by month.

**Comment by Vladabdf** [comment]
#305 when the fontimage swizzling was fixed.

**Comment by pablo5425** [comment]
actually, icons were fine when fonts had wrong dimensions. so the problem started somewhere between both releases. that is all i know

**Comment by Topaz-Reality** [comment]
This issue is fixed as of #328 and #329. This can be closed.
