### ISSUE TITLE
Image Viewer should be able to check if pngquant has been supplied in the root folder

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#331]
The Image Viewer contains an option to use pngquant. Upon enabling the option, the program should scan the folder it's running in for pngquant, and if it is not detected, prompt the user to download their appropriate binary file [here](https://pngquant.org/).

Example of pngquant being enabled but not detected:
![image](https://user-images.githubusercontent.com/20749232/102724638-ef4e6f80-42de-11eb-8ffb-0fa8263639c1.png)

**Comment by Xeeynamo** [comment]
That would be cute to have

**Comment by Topaz-Reality** [comment]
Addressed in Merged PR #351.

**Comment by Vladabdf** [comment]
Thanks for the work. 💯
