### ISSUE TITLE
MapStudio Crash

### ISSUE THREAD

**Issue by 1234567890num** [Xeeynamo/OpenKh#342]
MapStudio crashes when trying to open b_00 spawn point in eh06 (Nothing's Call)

**Comment by Topaz-Reality** [comment]
Could you provide the error messages that pop up (if any) and some screenshots to help the devs understand the issue?
Thanks a ton for the issue.

**Comment by 1234567890num** [comment]
There's no error messages before the crash. In the scenario presented in the screenshot the progam will crash immediately upon clicking.

![crash](https://user-images.githubusercontent.com/53823593/103334268-4d2f4400-4aa3-11eb-9d0d-a6f7aee6e893.png)

**Comment by Xeeynamo** [comment]
It seems to be caused by `obj\M_EX870.mdlx` as MapStudio (`ObjEntryController.cs:74`) always expect a texture. The 3D model is a white pyramid and it looks like to be unused in the final game too.

**Comment by Vladabdf** [comment]
Fixed with #350.
