### ISSUE TITLE
IdxImg KH2US support

### ISSUE THREAD

**Issue by DanielSinth** [Xeeynamo/OpenKh#348]
Hi guys, first of all thank you very much for the amazing work you have done so far.
May I ask you to add support for KH2US.iso for the IdxImg tool?

OpenKh.Command.IdxImg inject -idx 3825664 KH2US.iso <InputFile> <FilePath>
FATAL ERROR: Specified argument was out of the range of valid values. (Parameter 'count')

ISO block for KH2.IDX. By default is 1840 for KH2FM
**for KH2US (0x3A6000, dec 3825664)**
ISO block for KH2.IMG. By default is 671693 for KH2FM
**for KH2US (0x459000, dec 4558848)**

**Comment by Topaz-Reality** [comment]
I will look into this but it seems that the values you specified are too big for KH2US, perhaps?

**Comment by Rikux3** [comment]
IdxImg uses specific values for 2FM currently, which is why any other version isn't supported yet.

**Comment by DanielSinth** [comment]
@Topaz-Reality
> I will look into this but it seems that the values you specified are too big for KH2US, perhaps?

![IDX](https://user-images.githubusercontent.com/38701288/103487208-c5379a00-4e14-11eb-8dfc-c4d048a0852a.jpg)

**Comment by Topaz-Reality** [comment]
@DanielSinth 
Yea, it is asking you for **blocks**, so you need to divide the value you input by 2048.
So, 3825664 / 2048 = **1868** & 4558848 / 2048 = **2226**

I will implement a dynamic file seeking method to this so manual labor is not necessary. But in the meantime, please use the given values above.

**Comment by DanielSinth** [comment]
Thanks a lot!
Now it works without any problems.
Should I close the issue?

**Comment by Topaz-Reality** [comment]
We should close the issue after and if #349 is tested and accepted. In my opinion, anyways.

**Comment by Topaz-Reality** [comment]
Solved as of #349. Thanks for the issue!
