### ISSUE TITLE
It may make sense to upstream your KaitaiStruct specs into https://github.com/kaitai-io/kaitai_struct_formats/

### ISSUE THREAD

**Issue by KOLANICH** [Xeeynamo/OpenKh#386]
https://github.com/Xeeynamo/OpenKh/blob/4adf3c00214d9b5fe0a233f4c5b1142b470f841c/docs/kh2/file/type/bgm.md
https://github.com/Xeeynamo/OpenKh/blob/4adf3c00214d9b5fe0a233f4c5b1142b470f841c/docs/kh2/file/type/idx.md
https://github.com/Xeeynamo/OpenKh/blob/6c8b3d2bcdd7b99f05b9e71f82d6d31566e4fd35/docs/kh2/file/type/bar.md

**Comment by Topaz-Reality** [comment]
I would prefer against it. KaitaiStructFormats contain standardized formats by ISO and the like for many operating systems, file systems and the like. Pushing these non-standard formats to that repo is counter intuitive at best in my opinion.

However, I will wait input of one more collaborator before closing this issue. Perhaps they think differently than I do on this topic.

**Comment by Xeeynamo** [comment]
Hi @KOLANICH what would be the reason and the impact of the change you suggested? Sorry but I fail to understand how it would help.

**Comment by KOLANICH** [comment]
>I would prefer against it. KaitaiStructFormats contain standardized formats by ISO and the like for many operating systems, file systems and the like.

Not quite. Especially in `game` dir.

>Hi @KOLANICH what would be the reason and the impact of the change you suggested?

1. Sometimes the compiler is upgraded with new features (maybe even non-backward-comaptible) improving the old ones.

i.e.

```yaml
repeat: expr
repeat-expr: ...
```

to

```yaml
repeat:
  expr: ...
```
.

So having all the specs in one central place makes it easier to do such bulk changes.

2. TBH: just to increase visibility of the specs and KS project. More specs -> more people involved -> more specs and more features -> closer to making it a de-facto standard of specifying binary stuff (i.e. I'd like to see IETF RFCs' authors (and authors of other docs) originally specifying binary stuff in KS instead of ASCII-pseudotables or free-form text, so I don't have to semi-manually convert them into KS in order to get working parsers).

**Comment by Topaz-Reality** [comment]
I see, I did not know about the ``game`` directory.
I will get myself out of this and let @Xeeynamo decide.

**Comment by Xeeynamo** [comment]
To be honest they are there in the docs but they are actually not used. I was even thinking to archive or remove them at some point honestly to keep both codebase and docs more compact. Your idea would have been a good one if we would actively using it. Closing this issue.

**Comment by Delta-473** [comment]
Most archive types are getting updated atm so the few KSF's we have are getting out of date. I would suggest that you or someone interested in this will come back in a few weeks and check the code. I know it's closed just giving my perspective.
