### ISSUE TITLE
[BUG] - pngquant download link crash

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#424]
**OpenKH Build**
Release 1393

**OpenKH Program**
OpenKh.Tools.ImageViewer

**Describe the Bug**
Clicking the pngquant download link in Image Viewer causes the program to crash after enabling pngquant and the program not being detected.

**To Reproduce**
1. Open OpenKh.Tools.ImageViewer
2. Go to Edit > enable "Use pngquant"
3. Click the download link in the dialogue box that shows up
4. Stare at your screen in awe as you wonder why that caused the program to crash

**Expected behavior**
The link should open a tab in the current default assigned web browser with which the user would download the pngquant Windows binary zip package.

**Additional context**
@Topaz-Reality :^)

**Comment by Topaz-Reality** [comment]
This is an issue with the Xe toolset. Will investigate closer, but for now, refer to the added label.

**Comment by Topaz-Reality** [comment]
Dang, I have forgotten I have delinked THAT particular tool from the Xe Toolset.
I will see if this issue is fixed by the merge of #433
