### ISSUE TITLE
[BUG] - Cannot "Save as..." with fontimage.bar in Image Viewer

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#426]
**OpenKH Build**
Release 393

**OpenKH Program**
OpenKh.Tools.ImageViewer

**Describe the Bug**
Selecting "Save as..." with fontimage.bar either creates an IMZ file with IMGDs within instead of a BAR with raw bitmaps, or crashes the program.

**To Reproduce**
1. Open Image Viewer
2. Open fontimage.bar
3. Make changes
4. Click "Save as..."
5. Wonder with slight contempt and annoyance why IMZ is the only allowed file type to save as
6. Save anyway because you're persistent and hope for the best
7. Crash. Or don't. Regardless, you have a useless file

**Expected behavior**
Save fontimage.bar properly.

**Screenshots**
[Snip](https://i.vgy.me/I5wA1Z.png)

**Additional context**
 The crash happens <1% of the time with testing and is probably related to this issue regardless.
This entire issue is related to #425.
The program needs support for raw bitmap basically. Pls give.

**Comment by Topaz-Reality** [comment]
Extremely related to #425 to be considered a duplicate. Closing.
