### ISSUE TITLE
Unable to delete IMD files from Windows Explorer

### ISSUE THREAD

**Issue by Xeeynamo** [Xeeynamo/OpenKh#430]
**OpenKH Build**
1402

**OpenKH Program**
WinShell

**Describe the Bug**
Unable to delete IMD files from Windows Explorer

**To Reproduce**
Extract few images with Image Viewer from an IMZ as IMD then try to delete those IMD.

**Expected behavior**
IMDs should be deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/6128729/108118878-e091f800-7096-11eb-9cb5-68dfe817d4ae.png)

**Additional context**
openkh is c00l

**Comment by Topaz-Reality** [comment]
Thank you for your issue about the pinnacle of engineering that is WinShell.
Truly the best toolset in OpenKH to date, better than all else!
I will address this issue as soon as possible.
