### ISSUE TITLE
[FEATURE] - Add progress bar to OpenKh.Tools.IdxImg

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#435]
**Describe the solution you'd like**
Add a progress bar either as a child window to the tool or built into the main one during the extraction process.

**Describe alternatives you've considered**
Detect the number of files within the IDX/IMG and show the number of files extracted over the total number rather than an arbitrary bar.

**Comment by Topaz-Reality** [comment]
This has been discussed for quite a while.
I will look into it, although, I cannot promise if I can address it.
