### ISSUE TITLE
MapStudio tr02 Crash

### ISSUE THREAD

**Issue by 1234567890num** [Xeeynamo/OpenKh#444]
**OpenKH Build**
Release 301

**OpenKH Program**
MapStudio

**Describe the Bug**
MapStudio crashes upon trying to load tr02 map.

**To Reproduce**
1. Open MapStudio
2. Load KH2 extracted & merged folder
3. Click tr02
4. Watch as MapStudio closes itself without any error message

**Expected behavior**
The MapStudio shows the map (Game Grid in Space Paranoids)

**Comment by Vladabdf** [comment]
Execute map studio with the command prompt and then open the trouble map. What error shows up in the command line?

**Comment by 1234567890num** [comment]
What's a trouble map?

**Comment by Delta-473** [comment]
trouble map = the map that crashes the editor. So load tr02 through the command prompt. :)

**Comment by 1234567890num** [comment]
What argument is needed to run it through command prompt?

**Comment by Vladabdf** [comment]
> What argument is needed to run it through command prompt?

Just type the name of the program then use it like normal.

**Comment by 1234567890num** [comment]
Nothing shows up on the command prompt if I run it that way.

**Comment by Delta-473** [comment]
Do you have visual studio to build it yourself? Then you can run in debug mode and it will show where it hangs.

**Comment by 1234567890num** [comment]
No, I don't. Sorry.

**Comment by 1234567890num** [comment]
Same problem happens with tr07 (Solar Sailer)

**Comment by Delta-473** [comment]
Idk if this is the proper place to fix it but just adding a null check in MapRenderer.cs fixes the issue. As this map load correct in engine iirc.

![image](https://user-images.githubusercontent.com/13855042/110029881-4e941b80-7d35-11eb-874e-cd826b25cfa8.png)

**Comment by Xeeynamo** [comment]
Fixed in #466 as @Delta-473 correctly pointed out.
