### ISSUE TITLE
[BUG] - Mod Manager - Audio Desync Issues

### ISSUE THREAD

**Issue by tommadness** [Xeeynamo/OpenKh#460]
**OpenKH Build**
21.03.21.2

**OpenKH Program**
Mod Manager

**Describe the Bug**
Timing reliant audio desyncs over time.

**To Reproduce**
1. Enter Atlantica (Kingdom Hearts 2: Final Mix)
2. Peform "Swim This Way"
3. Vocal and Backing audio slowly become out of sync, potentially due to scene loading stutters.

**Expected behavior**
Audio remains in sync throughout the entirety of Atlantica

**Screenshots**
https://www.youtube.com/watch?v=PxosG-RPA1g

**Additional context**
Tested with and without cheats. Tested on PCSX2-EX. Tested on Solid State and Hard Drives.

**Comment by Xeeynamo** [comment]
I am not sure if I would classify it as a bug. It affects loading times and on a rhythmic mini-game it is easy to go out of sync. I am not sure if I can do anything about it honestly.
