### ISSUE TITLE
[BUG] - Opening ModsManager via shortcut changes configuration location

### ISSUE THREAD

**Issue by snelson3** [Xeeynamo/OpenKh#469]
**OpenKH Build**
21.03.24.4

**OpenKH Program**
Mods Manager

**Describe the Bug**
If you create a shortcut for the Mods Manager and move it outside the openkh folder, when you start up the mods manager it creates the modmanager.yml/mods/mod/etc in the folder containing the shortcut, instead of using the ones in the openkh folder.

**To Reproduce**
1. Create a shortcut to the mods manager
2. Move it to your desktop
3. Open mods manager
4.  See "mods" folder created on your desktop

**Expected behavior**
To have it load using the "mods" folder inside the mod manager

**Additional context**
It is pretty annoying to find the executable for mods manager inside the executable, so it would be ideal to have a shortcut.

**Comment by Xeeynamo** [comment]
If you go too the shortcut properties, is the "Start in" the same path as the openkh folder?
![image](https://user-images.githubusercontent.com/6128729/112986234-28f20a80-9159-11eb-8a8b-283819c121b3.png)

**Comment by snelson3** [comment]
Wasn't a bug, was an issue with windows creating a relative path shortcut
