### ISSUE TITLE
Discord invite dead

### ISSUE THREAD

**Issue by Rahlii** [Xeeynamo/OpenKh#50]
technically counts as an issue in the repository

the Discord link [on this page](https://github.com/Xeeynamo/OpenKh/blob/master/CONTRIBUTING.md) is invalid.

I'm not a programmer myself but as a game modder I take great interest in this project 👀

**Comment by Xeeynamo** [comment]
Thank you for reporting the issue!
I just created a Pull Request to update the link on the contribution file. While it will be reviewed, be free to follow the new invite link from the change I made: https://github.com/Xeeynamo/OpenKh/pull/51

Closing the issue as resolved!
