### ISSUE TITLE
Certain 2ld files crash in the Layout Viewer, but it's inconsistent

### ISSUE THREAD

**Issue by Rikux3** [Xeeynamo/OpenKh#53]
Error in Xe.Drawing.Direct3D/Drawing.Surface.cs, Line 155.
`Texture.Description` is null, so accessing Width causes an NullReferenceException.

First open event/layout/jp/tt_khend.2ld and then event/layout/jp/lm_204s_2.2ld to reproduce.

![2019-12-08 15_28_35-Window](https://user-images.githubusercontent.com/29046361/70390880-75975c80-19cf-11ea-95ff-5276f2561695.png)

**Comment by Xeeynamo** [comment]
Thanks for opening the issue. This is definitively a bug. I will have a look on that file ASAP!

**Comment by Xeeynamo** [comment]
Fixed in https://github.com/Xeeynamo/OpenKh/pull/79. I am requesting you as a reviewer to double-check if everything is all right!

**Comment by Rikux3** [comment]
Indeed fixed with #79 .
