### ISSUE TITLE
Line breaks cannot be added in the text editor

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#54]
Line breaks already present can be removed but not re-added unless you undo (ctrl+z). Entirely new line breaks cannot be added at all, even when trying to copy and paste them.

**Comment by Vladabdf** [comment]
I was uninformed that a custom string map is being used. I will work on making proper documentation for this more user friendly format ASAP!

**Comment by Xeeynamo** [comment]
On the editor there is a `{:newline}` code to insert new lines. It can be patched to add new lines using the Enter button and let that be more user friendly. So I would just label this as a enhancement rather than bug.
