### ISSUE TITLE
Missing feature- kh save editor

### ISSUE THREAD

**Issue by Darkbabe2** [Xeeynamo/OpenKh#543]
Dear friend i would like to ask you if its possible to update ffviiremake materia list so it has ramuh materia?, as right now it show it as a missing feature on tab. If you open an intersmission save file, it has it, but blank, so i can't add it on main game. I would really appreciated if you check it. I will wait for your respond. Keep up the great job you are doing. I think the item id code might be this 14010 but im not sure.
![error](https://user-images.githubusercontent.com/97826814/149653878-c53893a3-c854-418c-99dc-34a391bd41f0.png)

**Comment by Vladabdf** [comment]
This is not the save editor, nor does OpenKH have any inherent relationship with it. They are two entirely separate projects with two entirely separate goals.
