### ISSUE TITLE
[BUG] - IdxImg tool fail to extract DDS

### ISSUE THREAD

**Issue by gledson999** [Xeeynamo/OpenKh#611]
**OpenKH Build**
[OpenKH - 20220614.2](https://github.com/Xeeynamo/OpenKh/releases/tag/release-403)

**OpenKH Program**
OpenKh.Command.IdxImg

**Describe the Bug**
This bug occurs when you go to extract pkg/hed, all DDS will be extracted cut in half as shown in the image below.
![image](https://user-images.githubusercontent.com/31073450/174466196-e6c4b48b-8fcb-4bca-832c-68a4cbf05e01.png)

This other image is how it should be extracted without being cropped for example.
![image](https://user-images.githubusercontent.com/31073450/174466204-787f4d23-38c1-49e0-98e8-bae3bd1b49c3.png)
Opening the DDS image in a hex editor, it is cropped exactly at position 0xE540. It is cropped and replaced with 00 until the end of the image.
![image](https://user-images.githubusercontent.com/31073450/174466343-8daf9e68-d84f-446c-a8e9-2db8303e9b5a.png)

**Comment by VaultLink** [comment]
This happens the same with all other file type as shown with the DDS above, cutting off at seemingly random locations and filling the rest of the file with 00's.
The last build that OpenKh.Command.IdxImg was functional in was build 1859

**Comment by Xeeynamo** [comment]
Thank you for the extremely useful details! I was instantly able to pinpoint where the problem was located. I created the PR #612 and I hope it fixes the issue.

**Comment by gledson999** [comment]
> Thank you for the extremely useful details! I was instantly able to pinpoint where the problem was located. I created the PR #612 and I hope it fixes the issue.

Great, once everything is merged and released, I'll do some testing.
