### ISSUE TITLE
Null Values (Whitespaces) Showing in Objentry Editor

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#62]
Null values (whitespace) in the Objentry Editor are rendering as squares instead of spaces as they should be. Riku has tried to reproduce it but cannot, and the issue is present with other people as well.

![image](https://user-images.githubusercontent.com/20749232/71757727-0a259b00-2e66-11ea-90d6-fd0b12d3ae9a.png)

**Comment by Xeeynamo** [comment]
Are you using Wine on Linux?

**Comment by Vladabdf** [comment]
Windows 10 Pro, build 1809

**Comment by Xeeynamo** [comment]
This should fix it https://github.com/Xeeynamo/OpenKh/pull/63

Can you double-check before accepting the pull request?

**Comment by Vladabdf** [comment]
Confirmed after testing myself and having another person test. Thanks Xeeynamo!
