### ISSUE TITLE
Add an Option to Load sys.bar in Kh2SystemEditor

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#74]
This would allow item names to be attached to the appropriate item ID, making identifying the IDs easier.
(Suggested by Keytotruth)

**Comment by Xeeynamo** [comment]
As far I know it is already possible to do so 

![image](https://user-images.githubusercontent.com/6128729/74018286-8b081300-498d-11ea-9360-0e78e970ee1a.png)

Am I missing something?

**Comment by Vladabdf** [comment]
This is what it looks like for me. Maybe I'm missing something, but the "Load MSG Only" option under File > Support files only allows me to load 'place.bin' from the msg folder, which I've never even known to exist until now. I have no idea what that file is for, and loading it doesn't do anything either.
![image](https://i.vgy.me/NNKxvK.png)

**Comment by Xeeynamo** [comment]
Have you tried to see "All files"?

**Comment by Vladabdf** [comment]
This issue was an oversight by myself and Truthkey. After the latest [commit](https://github.com/Xeeynamo/OpenKh/commit/8c13d9cb37e5142077ce069f49ea0dba96644c77), the solution is more obvious and easier to access.
