### ISSUE TITLE
Kh2SystemEditor Crashes When Loading KH2.IDX

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#75]
Program loads for a few seconds, remains fine, then silent crash with no error.

**Comment by Xeeynamo** [comment]
I was not able to replicate the issue. The IDX is loaded just fine and all the relative text are correctly binded to the Item IDs. Are you using an IDX/IMG pair that contains Japanese text?

**Comment by Xeeynamo** [comment]
Actually I just tried with Japanese text and it just show weird text. But it does not crash.

**Comment by Vladabdf** [comment]
Yeah, I loaded 03system.bin from the unmodified game dump and the IDX from the same dump. I'm able to replicate it consistently with a 100% chance of the crash occurring.

**Comment by Xeeynamo** [comment]
Does the same error still occurred after https://github.com/Xeeynamo/OpenKh/pull/76 being merged?

**Comment by Vladabdf** [comment]
The program no longer crashes and displays an appropriate error.

![image](https://i.vgy.me/pUS1JS.png)

Program works as intended when both the IDX and IMG are supplied.
