### ISSUE TITLE
KH2 Text Editor Bloats File Size

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#89]
Unmodified English-patched sys.bar is 96kb. After a few simple edits, 108kb. The only thing changed between these files (attached) is the 183 instances of "Sora" being replaced with "Sanza". I've deduced that the likely problem is new text strings are being declared somehow but with no text appended to them. While the file doesn't crash the game, it causes much of the text to appear blank, likely because of an offset that's happening.
Workflow: Open fontimage and fontinfo.bar in editor -> Open sys.bar -> Export as YAML -> Open in Sublime Text, find all instances of Sora -> Replace with Sanza -> Save, reimport via OpenKH Text Editor -> Save new sys.bar
[sys.bar.zip](https://github.com/Xeeynamo/OpenKh/files/4381300/sys.bar.zip)

**Comment by Xeeynamo** [comment]
I did some testing and this behaviour of the inflated sys.bar happens only with the patched one.
The patched version uses a technique to re-use messages that are exactly the same to save space.

The original file behaves in a different way and the Text Editor is built to replicate the original behaviour. But an optional save option to "optimize" the exported text can be built in the editor!

**Comment by Rikux3** [comment]
Saving the attached file optimized seemed to have worked (i fought Terra and Zexion, which in the past had the same issue for me).
