### ISSUE TITLE
Support for ".fac" Filetype Which Contains Menu Icons

### ISSUE THREAD

**Issue by Tomk1004** [Xeeynamo/OpenKh#92]
the ".fac" file is headerless, and is simply several ".imd" files one after another. the first .imd file of the .fac file opens in "KH2 Image Editor" while the rest don't appear or are acknowledged by the tool, and the "OpenKH Image Viewer" opens the first ".imd" image as well, but only after the ".fac" file has been renamed to ".imz". 
a small modification to the current viewer that reads from one "IMGD" tag to the next "IMGD" tag, and displays each seperate .imd file could work

below is a link to a .fac file found in "KH2/menu/fm":
https://drive.google.com/open?id=179VWey3UdvTFNWNmIjlZ7ugNm5M7Nwmb

**Comment by Vladabdf** [comment]
I would like to append the fact that the OpenKH viewer can indeed open them without changing the file extension. You just have to set the program to look at "All files" instead of only the supported ones. It picks up on image data, just not all of the images.

**Comment by Xeeynamo** [comment]
Fixed in #93 . Please confirm it before closing this issue.

**Comment by Tomk1004** [comment]
works perfectly with KH2FM .fac files, great job
